name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  otp: ^3.1.4
  flutter_bloc: ^8.1.3
  go_router: ^14.0.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  http: ^1.1.0
  iconify_flutter: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/illustrations/
    - assets/images/illustrations/image2.png

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
